services:
  auth:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: auth
    ports:
      - 3000:3000
    environment:
      NODE_ENV:
      SELECTED_SETUP:
      MONGO_URI:
      REDIS_URI:
      REDIS_PORT:
      REDIS_PASSWORD:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      GOOGLE_CALLBACK_URL:
      EMAIL_USER:
      EMAIL_PASS:
      EMAIL_SERVICE:
      PASSWORD_REQUIREMENTS:
      ACTION_URL:
    depends_on:
      - mongo
      - cache
      - mongo-express
    command: ["npm", "start"]

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: >
      mongod --quiet --logpath /dev/null

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_LOGGING__LEVEL: error

  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81