import { Container } from "inversify";
import IUserController from "../controllers/contracts/user-controller-contract";
import { TYPES } from "./types";
import UserController from "../controllers/user-controller";
import IUserService from "../services/contracts/user-service-contract";
import UserService from "../services/user-service";
import IUserRepository from "../domain/repositories/user-repository";
import UserInmemoryRepository from "../infrastructure/persistence/inmemory/user/user-inmemory-repository";
import IPasswordManager from "../services/contracts/password-manager";
import BcryptAdapter from "../infrastructure/password/bcrypt-adapter";
import IAuthService from "../services/contracts/auth-service-contract";
import AuthService from "../services/auth-service";
import AuthController from "../controllers/auth-controller";
import IAuthController from "../controllers/contracts/auth-controller-contract";
import IEncrypter from "../services/contracts/encrypter-contract";
import IRefreshTokensStore from "../services/contracts/refresh-tokens-store";
import { EventEmitter } from "events";
import { EventHandlers } from "../events/event-handlers";
import { CreateUserSendEmailHandler } from "../events/create-user-send-email.event";
import IEmailClient from "../services/contracts/email-client";
import DummyEmailClient from "../infrastructure/email/dummy-email-client";
import IVerifyToken from "../api/middlewares/contracts/verify-token.contract";
import { DI_CONFIG } from "../config";
import ISetupDb from "../infrastructure/setup/contracts/setup-db.contract";
import ISetupRefreshTokenStore from "../infrastructure/setup/contracts/refresh-token-store.contract";
import IAuthIAMService from "../services/contracts/iam-service-contract";
import PassportIAM from "../infrastructure/passport/passport-iam";

const myContainer = new Container();
myContainer.bind<IUserController>(TYPES.IUserController).to(UserController);
myContainer.bind<IUserService>(TYPES.IUserService).to(UserService);
myContainer.bind<IUserRepository>(TYPES.IUserRepository).to(DI_CONFIG.IUserRepository).inSingletonScope();
myContainer.bind<IPasswordManager>(TYPES.IPasswordManager).to(DI_CONFIG.IPasswordManager);
myContainer.bind<IAuthService>(TYPES.IAuthService).to(AuthService);
myContainer.bind<IAuthController>(TYPES.IAuthController).to(AuthController);
myContainer.bind<IEncrypter>(TYPES.IEncrypter).to(DI_CONFIG.IEncrypter);
myContainer.bind<IRefreshTokensStore>(TYPES.IRefreshTokensStore).to(DI_CONFIG.IRefreshTokensStore).inSingletonScope();
myContainer.bind(TYPES.EventEmmiter).toConstantValue(new EventEmitter());
myContainer.bind<EventHandlers>(EventHandlers).toSelf();
myContainer.bind<CreateUserSendEmailHandler>(TYPES.CreateUserSendEmailHandler).to(CreateUserSendEmailHandler);
myContainer.bind<IEmailClient>(TYPES.IEmailClient).to(DummyEmailClient);
myContainer.bind<IVerifyToken>(TYPES.IVerifyToken).to(DI_CONFIG.IVerifyToken);
myContainer.bind<ISetupDb>(TYPES.ISetupDb).to(DI_CONFIG.ISetupDb);
myContainer.bind<ISetupRefreshTokenStore>(TYPES.ISetupRefreshTokenStore).to(DI_CONFIG.ISetupRefreshTokenStore);
myContainer.bind<IAuthIAMService>(TYPES.IAuthIAMService).to(PassportIAM);

export { myContainer };